# config.make generated by configure script
POCO_CONFIG = Linux
POCO_BASE = /home/yhy/cpp_environment_setup/poco/v1.6.0/poco-1.6.0-all
POCO_BUILD = /home/yhy/cpp_environment_setup/poco/v1.6.0/poco-1.6.0-all
POCO_PREFIX = /opt/devbus/poco/v1.6.0
POCO_FLAGS = 
OMIT = 
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_PREFIX
export POCO_FLAGS
